### ISSUE TITLE
[Request] Ability to login with an account, in order to download higher resolution videos

### ISSUE THREAD

**Issue by nilobones** [Nukesor/pornhub-dl#1]
I found this application today, and I love it!

Would it be possible to add the ability to supply the application with login credentials to a Pornhub premium account, in order to download videos with higher resolution?

**Comment by Nukesor** [comment]
This should be possible. I don't own a premium accoun, thereby I cannot really test this :D

**Comment by Nukesor** [comment]
Implemented
