### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by badsector998** [Nukesor/pornhub-dl#10]
I tried to install the script. The first step is done but when i run the `poetry run python ./pornhub-dl` it returns as follow :

> Traceback (most recent call last):                                                                                        File "C:\Users\John\Downloads\pornhub-dl-master\pornhub-dl-master\pornhub-dl", line 4, in <module>                        from pornhub import main                                                                                              File "C:\Users\John\Downloads\pornhub-dl-master\pornhub-dl-master\pornhub\__init__.py", line 4, in <module>               from pornhub.db import create_db                                                                                      File "C:\Users\John\Downloads\pornhub-dl-master\pornhub-dl-master\pornhub\db.py", line 8, in <module>                     from pornhub.config import config                                                                                     File "C:\Users\John\Downloads\pornhub-dl-master\pornhub-dl-master\pornhub\config.py", line 15, in <module>                with open(config_path, "w") as file_descriptor:                                                                     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\John/.config/pornhub_dl.toml'

any idea how to fix this? i thought the command was to create that file but instead it was looking for that file as for my case.

**Comment by Nukesor** [comment]
To be honest, this whole project hasn't been built with Windows in mind :sweat_smile: 
It might be, that this is an easy fix, but I have no experience with this.

I also haven't used this little side-project since roughly a year. Expect things to not fully work.
Pornhubs page structure changed quite a bit in the last few months and the parser might no longer work.

**Comment by badsector998** [comment]
> To be honest, this whole project hasn't been built with Windows in mind :sweat_smile: 
> It might be, that this is an easy fix, but I have no experience with this.
> 
> I also haven't used this little side-project since roughly a year. Expect things to not fully work.
> Pornhubs page structure changed quite a bit in the last few months and the parser might no longer work.

Ohh man :((

I wish this still work.. even if i want to continue or fork the repo and make my own changes.. i don't know how your codes work lol.. i dont even have any experience on developing web apps, let alone the web structure and how pornhub "hide" their source 😂

**Comment by Nukesor** [comment]
I know :D

It's kind of sad to see projects get old, but i just don't have the time to take care about all them. Gotta prioritize ;)

As long as you are semi-proficient in Python, you could always try and fix it! I try to properly document my code, even in my half-assed hobby/fun projects.

**Comment by badsector998** [comment]
Understandable.. i have my own priority too.. but f it.. i'll give it a try.

Btw, thanks for the lead.. :)

**Comment by Nukesor** [comment]
Closing the issue for now :)
