### ISSUE TITLE
Database migrations fail due to missing dependencies

### ISSUE THREAD

**Issue by Uku-Dge** [Nukesor/pornhub-dl#13]
```
poetry run alembic upgrade head                                         16:55:11
Traceback (most recent call last):
  File "/home/*************/pornhub-dl/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/**********/pornhub-dl/.venv/lib/python3.8/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
/// ...
home/********/pornhub-dl/migrations/env.py", line 12, in <module>
    from pornhub.db import base  # noqa
ModuleNotFoundError: No module named 'pornhub.db
```

From env.py lines 12-14:
```
from pornhub.db import base  # noqa
from pornhub.models import *  # noqa
from pornhub.config import config as pornhub_config  # noqa
```

Seems that lines 12 and 14 don't correspond to anything on the file system. I don't see the folders listed on .git-ignore, so I'm not sure if they are supposed to be generated by some command line, or really what to do about them being missing

@Nukesor Do you have any memory of what this is? I'm not familiar with poetry/alembic/python dev so just trying to brute force my way through this

**Comment by Uku-Dge** [comment]
Found the fix, needed to update the lines in env.py 12-14 to the below. I guess there was some refactoring and the files were moved to core folder

`from pornhub.core.db import base  # noqa
from pornhub.models import *  # noqa
from pornhub.core.config import config as pornhub_config  # noqa`

I can put out a PR for this later

**Comment by Nukesor** [comment]
Thanks for reporting this :)
I overlooked this when refactoring the project's structure.
Since this is a rather critical bug, I went ahead and already fixed this on master.
