### ISSUE TITLE
"user" doesn't support dash symbol

### ISSUE THREAD

**Issue by MySadCaptain** [Nukesor/pornhub-dl#2]
Hey, thanks for making this great tool! I found that it seems doesn't support user's name with dash symbol. For example:
`poetry run python runner.py user leolulu` works
but `poetry run python runner.py user blaire-ivory` doesn't work and got the 

> Exception: Couldn't detect type for user blaire-ivory

Can you fix it?

Thank you!

**Comment by MySadCaptain** [comment]
Hey, sorry about the previous post. I found that actually it has nothing to do with the dash symbol. The homepage for different porn stars are different. Some of them this link `https://www.pornhub.com/pornstar/name/videos` exist, like `https://www.pornhub.com/pornstar/riley-reid/videos`, but some of them don't exist like `https://www.pornhub.com/pornstar/blaire-ivory/videos`. Only `https://www.pornhub.com/pornstar/blaire-ivory` exists. Can you also add support to those who don't have a `https://www.pornhub.com/pornstar/name/videos` link?

Thank you!

**Comment by Nukesor** [comment]
Oook. Sorry for taking so long, I had a lot to do with my other projects.
The bug should be fixed ;)
