### ISSUE TITLE
Broadcast recording

### ISSUE THREAD

**Issue by kitt3911** [Nukesor/pornhub-dl#9]
I don’t know how much it fits in the concept of your project and how legal it is, but in my opinion it would be an interesting thought to be able to record video from online broadcasts

**Comment by Nukesor** [comment]
This is most likely not a task for this project.
It's basically a convenience wrapper around youtube-dl, which doesn't support streaming downloads.

Plus, I don't think that this is a legal area I want to explore. We're already in a very gray area.
